version: "3.2"
services:
  web:
    build: 
      context: ./web_interface
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./shared_files:/usr/src/app/shared
      - ./shared_files/db.sqlite3:/db.sqlite3
      - /usr/src/app
    ports:
      - "8000:8000"  
  camera:
    build: 
      context: ./cameras_docker
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./shared_files:/usr/src/app/shared
      - /usr/src/app
    ports:
      - "8081:8081" 
      - "1935:1935" 
      - "4444:4444" 
